# Generated by Django 5.0 on 2023-12-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locustTesting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
