# Generated by Django 3.2 on 2024-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenant_identifier', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
    ]
